version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend-app:
    build: .
    # ports:
      # - "4000:4000"
      # - "4000-40001:4000"
    # volumes:
    # - ./:/app:ro
    # - /app/node_modules
    environment:
      - PORT=4000
    # env_file:
    #   - ./.env
    depends_on:
      - backend-db
  backend-db:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      # named volume
      - mongo-db:/data/db
  backend-db-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:password@backend-db:27017/
    depends_on:
      - backend-db
  # backend-redis:
  #   image: redis

volumes:
  mongo-db:
